#include "keyboard.h"

/*The scancode for these letters*/
#define Q 0x10
#define P 0x19
#define A 0x1e
#define L 0x26
#define Z 0x2c
#define M 0x32
/*The size of number part and letter part of the keyboard*/
#define NUM_size 14
#define LETTER_size 42
/*Three different terminals*/
#define terminal_0 0
#define terminal_1 1
#define terminal_2 2
/*Flags for each function keys*/
static uint8_t shift;
static uint8_t caps;
static uint8_t ctrl;
static uint8_t alt;

/*The font data for mapping scancode to symbols*/
static uint8_t font_data_num[NUM_size] = {'\0', '\0', '1', '2', '3','4','5','6','7','8','9','0', '-', '='};
static uint8_t font_data_letter[LETTER_size] = {'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\r', '\0',
										 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', '\0', '\\',
										 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', '\0', '*', '\0', ' '};
static uint8_t font_data_num_shift[NUM_size] = {'\0', '\0', '!', '@', '#','$','%','^','&','*','(',')', '_', '+'};
static uint8_t font_data_letter_shift[LETTER_size] = {'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\r', '\0',
										 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '\"', '~', '\0', '|',
										 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '\?', '\0', '*', '\0', ' '};
/*
 * keyboard_int_handler
 *   DESCRIPTION: Handles the interrupts generated by the keyboard
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: perform according action of keyboard
 */ 
void keyboard_int_handler()
{
	/*Variables for take in and output the keyboard signal*/
	uint8_t scancode;
	uint8_t output;

	/*send_eoi(1);*/
	/*Read in the scancode from the port*/
	scancode = inb(KEYBOARD_PORT);
	/*Different scancode different cases.*/
	switch(scancode)
	{
		/*Function key part*/
		case LALT:
			alt = pressed;
			break;
		case LALT_re:
			alt = released;
			break;
		case LSHIFT:
		case RSHIFT:
			shift = pressed;
			break;
		case LSHIFT_re:
		case RSHIFT_re:
			shift = released;
			break;
		case CAPS:
			caps ^= pressed;
			break;
		case CTRL:
			ctrl = pressed;
			break;
		case CTRL_re:
			ctrl = released;
			break;
		/*Delete a char using back space*/
		case BACKSPACE:
			input_char_terminal(BACKSPACE_ascii);
			break;
		/*Send enter signal to terminal*/
		case ENTER:
			input_char_terminal(ENTER_ascii);
			break;
		/*Symbol key part*/
		default:
			/*Number*/
			if (scancode <= NUM_LIM)
			{
				/*Nothing is pressed*/
				if (!shift && !caps && !ctrl && !alt)
				{
					output = font_data_num[scancode];
					input_char_terminal(output);
					break;
				}
				/*Only shift is pressed*/	
				else if (shift && !caps && !ctrl && !alt)
				{
					output = font_data_num_shift[scancode];
					input_char_terminal(output);
					break;
				} 
				/*Only caps is pressed*/
				else if (!shift && caps && !ctrl && !alt)
				{
					output = font_data_num[scancode];
					input_char_terminal(output);
					break;
				}
				/*Shift and cpas is pressed*/
				else if (shift && caps && !ctrl && !alt)
				{
					output = font_data_num_shift[scancode];
					input_char_terminal(output);
					break;
				}
			}
			/*Letter*/
			else if (scancode <= LETTER_UP && scancode >= LETTER_DOWN)
			{
				/*The ctrl+l clear terminal*/
				if ((scancode == L) && (ctrl))
				{
					clear_terminal();
					break;
				}
				/*Nothing is pressed*/
				else if (!shift && !caps && !ctrl && !alt)
				{
					output = font_data_letter[scancode - LETTER_OFF];
					input_char_terminal(output);
					break;
				}	
				/*Only shift is pressed*/
				else if (shift && !caps && !ctrl && !alt)
				{
					output = font_data_letter_shift[scancode - LETTER_OFF];
					input_char_terminal(output);
					break;
				}
				/*Only caps is pressed*/
				else if (!shift && caps && !ctrl && !alt)
				{
					if ((scancode >= Q && scancode <= P) || 
						(scancode >= A && scancode <= L) ||
						(scancode >= Z && scancode <= M))
					{
						output = font_data_letter_shift[scancode - LETTER_OFF];
						input_char_terminal(output);
						break;
					}
					else
					{
						output = font_data_letter[scancode - LETTER_OFF];
						input_char_terminal(output);
						break;
					}					
				}
				/*Shift and cpas is pressed*/
				else if (shift && caps && !ctrl && !alt)
				{
					if ((scancode >= Q && scancode <= P) || 
						(scancode >= A && scancode <= L) ||
						(scancode >= Z && scancode <= M))
					{
						output = font_data_letter[scancode - LETTER_OFF];
						input_char_terminal(output);
						break;
					}
					else
					{
						output = font_data_letter_shift[scancode - LETTER_OFF];
						input_char_terminal(output);
						break;
					}		
				}
			}
			/*Switch terminal part*/
			else if (scancode >= LETTER_UP)
			{
				switch(scancode)
				{
					case F1:
						if (alt && !shift && !ctrl && !caps)
						{

							send_eoi(KEY_IRQ);
							switch_terminal(terminal_0);

							break;
						}
					case F2:
						if (alt && !shift && !ctrl && !caps)
						{

							send_eoi(KEY_IRQ);
							switch_terminal(terminal_1);

							break;
						}
					case F3:
						if (alt && !shift && !ctrl && !caps)
						{

							send_eoi(KEY_IRQ);
							switch_terminal(terminal_2);

							break;
						}
				}
			}

	}
	
	/*If unknow/useless key is pressed, end interrupt*/
	if(!((scancode == F1 || scancode == F2 || scancode == F3)&&(alt && !shift && !ctrl && !caps))) send_eoi(KEY_IRQ);

	return;
}








