#include "exceptions.h"
/*Exceptions.c:
handle all the exceptions 
generated by the hardware
which will print the error and 
a infinite loop*/


/*
 * division_by_zero
 *   DESCRIPTION: Show the division_by_zero exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */ 
void division_by_zero()
{
	//clear();
	printf("Division by zero exception\n");
	while(1)
	{

	}
}
/*
 * debug_exception
 *   DESCRIPTION: Show the debug_exception exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void debug_exception()
{
	//clear();
	printf("Debug exception\n");
	while(1)
	{

	}
}
/*
 * non_maskable_int
 *   DESCRIPTION: Show the non_maskable_int exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void non_maskable_int()
{
	//clear();
	printf("Non maskable interrupt\n");
	while(1)
	{

	}
}
/*
 * break_point
 *   DESCRIPTION: Show the break_point exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void break_point()
{
	//clear();
	printf("Breakpoint exception\n");
	while(1)
	{

	}
}
/*
 * into_overflow
 *   DESCRIPTION: Show the into_overflow exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void into_overflow()
{
	//clear();
	printf("overflow\n");
	while(1)
	{

	}
}
/*
 * out_of_bounds
 *   DESCRIPTION: Show the out_of_bounds exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void out_of_bounds()
{
	//clear();
	printf("BOUND Range Exceeded\n");
	while(1)
	{

	}
}
/*
 * invalid_opcode
 *   DESCRIPTION: Show the invalid_opcode exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void invalid_opcode()
{
	//clear();
	printf("Invalid Opcode (Undefined Opcode)\n");
	while(1)
	{

	}
}
/*
 * device_not_available
 *   DESCRIPTION: Show the device_not_available exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void device_not_available()
{
	//clear();
	printf("Device Not Available (No Math Coprocessor)\n");
	while(1)
	{

	}
}
/*
 * double_fault
 *   DESCRIPTION: Show the double_fault exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void double_fault()
{
	//clear();
	printf("Double Fault\n");
	while(1)
	{

	}
}
/*
 * co_segment_overrun
 *   DESCRIPTION: Show the co_segment_overrun exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void co_segment_overrun()
{
	//clear();
	printf("Coprocessor Segment Overrun\n");
	while(1)
	{

	}
}
/*
 * invalid_tss
 *   DESCRIPTION: Show the invalid_tss exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void invalid_tss()
{
	//clear();
	printf("Invalid TSS\n");
	while(1)
	{

	}
}
/*
 * segment_not_present
 *   DESCRIPTION: Show the segment_not_present exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void segment_not_present()
{
	//clear();
	printf("Segment Not Present\n");
	while(1)
	{

	}
}
/*
 * stack_fault
 *   DESCRIPTION: Show the stack_fault exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void stack_fault()
{
	//clear();
	printf("Stack-Segment Fault\n");
	while(1)
	{

	}
}
/*
 * general_protection
 *   DESCRIPTION: Show the general_protection exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void general_protection()
{
	/*For debugging use*/
	/*uint32_t error_code;

	asm volatile("popl %0" : "=r" (error_code));
	asm volatile("movl 4(%%esp), %0" : "=r" (error_code[1]));
	asm volatile("movl 4(%%esp), %0" : "=r" (error_code[2]));
	asm volatile("movl 4(%%esp), %0" : "=r" (error_code[3]));*/

	//clear();
	printf("General Protection Fault\n");
	/*printf("General Protection Fault: %x\n", error_code);*/

	while(1)
	{

	}
}
/*
 * page_fault
 *   DESCRIPTION: Show the page_fault exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void page_fault()
{
	int cr2val;
	asm volatile("movl %%cr2, %0" : "=r" (cr2val));

// 	int eflags;
// 	int tmp = 0xFFFFFEFF;
// 	asm volatile("movl %%EFLAGS_reg, %0" : "=r" (eflags));
// 	eflags = eflags&tmp;
// 	asm volatile("movl %0, %%EFLAGS_reg" : /* no outputs */ : "r" (eflags));

// 	pushf ; Pushes the current flags onto the stack
// pop ax ; Pop the flags from the stack into ax register
// push ax ; Push them back onto the stack for storage
// xor ax, 400h ; toggle the DF flag only, keep the rest of the flags
// push ax ; Push again to add the new value to the stack
// popf ; Pop the newly pushed into the FLAGS register
// ; ... Code here ...
// popf ; Pop the old FLAGS back into place
	//clear();
	printf("Page Fault: %x\n", cr2val);
	while(1)
	{

	}
}
/*
 * x87_floating_point
 *   DESCRIPTION: Show the x87_floating_point exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void x87_floating_point()
{
	//clear();
	printf("x87 FPU Floating-Point Error (Math Fault)\n");
	while(1)
	{

	}
}
/*
 * alignment_check
 *   DESCRIPTION: Show the alignment_check exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void alignment_check()
{
	//clear();
	printf("Alignment Check\n");
	while(1)
	{

	}
}
/*
 * machine_check
 *   DESCRIPTION: Show the machine_check exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void machine_check()
{
	//clear();
	printf("Machine Check\n");
	while(1)
	{

	}
}
/*
 * SIMD_floating_point
 *   DESCRIPTION: Show the SIMD_floating_point exception
 *   INPUTS: none
 *   OUTPUTS: none
 *   RETURN VALUE: none
 *   SIDE EFFECTS: Stuck in infinite loop
 */
void SIMD_floating_point()
{
	//clear();
	printf("SIMD Floating-Point Exception\n");
	while(1)
	{

	}
}



